name: Packer for GCE
author: Animesh rastogi <animesh.rastogicloud@gmail.com>
desscription: Custom Packer Github Action for Google Compute Engine

inputs:
  main_file: 
    description: Packer configuration file written in json or HCL
    required: true
  
  variable_file:
    description: File containing all the the variables for the Packer Confif file
    required: false

  working_directory:
    description: Directory which contains your configuration file and your var file. If not specified, the home directory is assigned as default.
    required: false
    default: '.'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  color: blue
  icon: clock 