name: CI/CD Pipeline
on:
  push:
    branches: [master]

jobs:
  packer-build:
    runs-on: ubuntu-latest
    steps:
    # Checking out the source Code
      - name: Checkout the Source Code
        uses: "actions/checkout@v3"
        with:
          ref: master

      - name: Configure Authentication with GCP
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.ACTIONS_SA_KEY }}"

      - name: Build AMI
        uses: ./
        with:
          main_file: main.json
          variable_file: variable
          working_directory: .github/iac/